<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$cmsHelper = $block->getLayout()->createBlock('Magento\Cms\Block\Block');
?>

<div class="container">
    <div class="row">
        <div class="col-sm-3">
            <a href="#">
                <div class="blocks"></div>
            </a>
        </div>
        <div class="col-sm-3">
            <a href="#">
                <div class="blocks"></div>
            </a>
        </div>
        <div class="col-sm-3">
            <a href="#">
                <div class="blocks"></div>
            </a>
        </div>
        <div class="col-sm-3">
            <a href="#">
                <div class="blocks"></div>
            </a>
        </div>
        <div class="col-sm-6">
            <a href="#">
                <div class="blocks"></div>
            </a>
        </div>
        <div class="col-sm-6">
            <a href="#">
                <div class="blocks"></div>
            </a>
        </div>
        <div class="col-sm-6">
            <a href="#">
                <div class="blocks"></div>
            </a>
        </div>
        <div class="col-sm-6">
            <a href="#">
                <div class="blocks"></div>
            </a>
        </div>


    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-4">
            <a href="#">
                <div class="blocks"></div>
            </a>
        </div>
        <div class="col-sm-4">
            <a href="#">
                <div class="blocks"></div>
            </a>
        </div>
        <div class="col-sm-4">
            <a href="#">
                <div class="blocks"></div>
            </a>
        </div>
        <div class="col-sm-6">
            <a href="#">
                <div class="blocks"></div>
            </a>
        </div>
        <div class="col-sm-6">
            <a href="#">
                <div class="blocks"></div>
            </a>
        </div>
    </div>
</div>

